version: '3'
services:

  puppeteer:
    container_name: puppeteer
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        HOST_UID: ${HOST_UID}
    image: local/puppeteer
    volumes:
      - ./app:/app
      - ./screenshots:/screenshots
    networks:
      - default

networks:
  default:
      driver: bridge